import localFont from "next/font/local";
import Navbar from 'app/components/navbar/'
import "./globals.css";

const montserratRegular = localFont({
  src: './fonts/Montserrat-Regular.ttf',
  variable: '--font-montserrat-regular',
  weight: '400',
});

const montserratSemiBold = localFont({
  src: './fonts/Montserrat-SemiBold.ttf',
  variable: '--font-montserrat-semi-bold',
  weight: '600',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${montserratRegular.variable} ${montserratSemiBold.variable}`}>
        <div style={{width:"100vw"}}>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
